project:
  name: "robinhood-stock-token-analytics"
  evidence: "0.9.1"

pages: ./pages

plugins:
  components:
    "@evidence-dev/core-components": {}
  datasources:
    "@evidence-dev/sqlite": {}
    evidence-connector-clickhouse: {}
